<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Inida</name>
   <tag></tag>
   <elementGuidId>2094a260-2446-41c1-8024-cbf5f70cb94a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.navFooterLine.navFooterLinkLine.navFooterPadItemLine > ul</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navFooter']/div[4]/ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>1c777d2c-e7db-43a2-aea3-807f953965de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AustraliaAlemaniaBrasilCanadáChinaEstados UnidosFranciaIndiaItaliaJapónMéxicoPaíses BajosPoloniaEmiratos Árabes UnidosReino UnidoSingapurTurquía</value>
      <webElementGuid>ebdb31c1-c4d5-4723-9cfe-3f33a3c95dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navFooter&quot;)/div[@class=&quot;navFooterLine navFooterLinkLine navFooterPadItemLine&quot;]/ul[1]</value>
      <webElementGuid>932a8110-e608-429c-8455-29ac1004615b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navFooter']/div[4]/ul</value>
      <webElementGuid>ce266649-a55a-46a8-8682-469ee53827b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IVA sobre los bienes'])[1]/following::ul[1]</value>
      <webElementGuid>86c6cca0-c3a3-4e37-a30e-5d7379ebca5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atención al Cliente'])[2]/following::ul[1]</value>
      <webElementGuid>48e443d1-599a-4102-ae6d-5297bf310bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul</value>
      <webElementGuid>7671462c-5f49-4955-b4e7-3223b6eb6ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = 'AustraliaAlemaniaBrasilCanadáChinaEstados UnidosFranciaIndiaItaliaJapónMéxicoPaíses BajosPoloniaEmiratos Árabes UnidosReino UnidoSingapurTurquía' or . = 'AustraliaAlemaniaBrasilCanadáChinaEstados UnidosFranciaIndiaItaliaJapónMéxicoPaíses BajosPoloniaEmiratos Árabes UnidosReino UnidoSingapurTurquía')]</value>
      <webElementGuid>9ccfa86a-c8d2-40d1-868c-297851823f24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
