<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Accept</name>
   <tag></tag>
   <elementGuidId>badf7665-511d-40be-9176-0f5fe7ac732f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sp-cc-accept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sp-cc-accept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aaa3d880-2a77-41f6-84b2-052b03b309f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sp-cc-accept</value>
      <webElementGuid>23f628fb-b240-407c-8524-24a34c19b2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f3da666e-a236-4952-aef2-d0fdb159e7bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accept</value>
      <webElementGuid>33f5e6cd-a5fc-4648-b35d-f681aea3f98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input celwidget</value>
      <webElementGuid>4ba03f68-b442-4965-8ed5-5cbddc192489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ce85c7d3-4ea8-4296-a9af-4fa21e10b888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>all</value>
      <webElementGuid>8cc40922-ebfb-436d-ab82-84b24050713d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>3i8coh-l6ledl-b077ps-m058i1</value>
      <webElementGuid>044b4b25-9414-4864-8cfb-c4b0a6a16e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sp-cc-accept&quot;)</value>
      <webElementGuid>41999b12-9b26-433f-956a-a6e704f3be6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sp-cc-accept']</value>
      <webElementGuid>072f1c2f-2122-41a0-865b-675f1d249495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='sp-cc']/div[2]/span/span/input</value>
      <webElementGuid>88053fa1-dad5-4e00-b231-27d6e2d924f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>29b51557-f8c0-4c91-a119-2b1df33deaf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sp-cc-accept' and @name = 'accept' and @type = 'submit']</value>
      <webElementGuid>669bb2c6-676a-4983-9e2c-a95fdb41d6f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
